export const ADD_TASK = 'ADD_TASK'

export const MARK_TASK_IMPORTANT = 'MARK_TASK_IMPORTANT'
export const MARK_TASK_TRIVIAL = 'MARK_TASK_TRIVIAL'

export const MARK_TASK_DONE = 'MARK_TASK_DONE'
export const MARK_TASK_NOT_DONE = 'MARK_TASK_NOT_DONE'

export const DELETE_TASK = 'DELETE_TASK'

//GLOBAL ACTIONS
export const MARK_ALL_TASKS_DONE = 'MARK_ALL_TASKS_DONE'
export const DELETE_INCOMPLETE_TASKS = 'DELETE_INCOMPLETE_TASKS'
export const DELETE_COMPLETED_TASKS = 'DELETE_COMPLETED_TASKS'
export const DELETE_ALL_TASKS = 'DELETE_ALL_TASKS'